source 'https://github.com/CocoaPods/Specs.git'

target 'Segment-Primer_Example', :exclusive => true do
  pod "Segment-Primer", :path => "../"
end

target 'Segment-Primer_Tests', :exclusive => true do
  pod "Segment-Primer", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
